#!/usr/bin/env python3
"""Validate reviewed rows and emit a browser ES module."""
import argparse
import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

def normalized(value):
    return re.sub(r"[^a-z0-9]+", "", value.lower())

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("js/generated-clues.js"), help="Runtime ES module (default: js/generated-clues.js)")
    parser.add_argument("--minimum", type=int, default=20, help="Approved clues required per letter")
    args = parser.parse_args()
    approved, errors, keys = defaultdict(list), [], set()
    with args.input.open(encoding="utf-8", newline="") as source:
        for number, row in enumerate(csv.DictReader(source), start=2):
            if row.get("status", "").strip().lower() != "approved": continue
            letter, clue, clue_id = row.get("letter", "").strip().upper(), row.get("clue_text", "").strip(), row.get("id", "").strip()
            if not re.fullmatch("[A-Z]", letter): errors.append(f"row {number}: invalid letter"); continue
            if not clue or not clue_id: errors.append(f"row {number}: clue text and id are required"); continue
            key = row.get("duplicate_key", "").strip() or normalized(clue)
            if key in keys: errors.append(f"row {number}: duplicate clue {key!r}"); continue
            if row.get("surface_answer", "").strip() and normalized(row["surface_answer"]) in normalized(clue): errors.append(f"row {number}: clue reveals surface answer"); continue
            item = {"id": clue_id, "letter": letter, "clue": clue, "mechanism": row.get("mechanism", "")}
            if row.get("topic"): item["topic"] = row["topic"]
            keys.add(key); approved[letter].append(item)
    counts = Counter({letter: len(approved[letter]) for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"})
    missing = [f"{letter}={counts[letter]}" for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" if counts[letter] < args.minimum]
    if missing: errors.append(f"minimum {args.minimum} not met: " + ", ".join(missing))
    if errors: raise SystemExit("Catalog rejected:\n- " + "\n- ".join(errors))
    payload = json.dumps(dict(approved), ensure_ascii=False, indent=2)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(f"// Generated by tools/compile_catalog.py\nexport const CLUES = {payload};\n", encoding="utf-8")
    print(f"Compiled {sum(counts.values())} clues to {args.output}")

if __name__ == "__main__": main()
